# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TwicketSegmentedControl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwicketSegmentedControl
    pod 'TwicketSegmentedControl', :git => 'https://github.com/justinackermann/TwicketSegmentedControl.git'
end

target 'TwicketSegmentedControlDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwicketSegmentedControlDemo

end
